// Emits an ExtendScript (.jsx) that builds the InDesign document natively.
// The scene graph is injected as an object literal; the builder below is ES3-safe.

import type { Scene } from "./types";

export interface EmitOptions {
  outDir: string; // absolute path; .indd/.idml/PNG proofs land here
  hardLineBreaks: boolean; // true = forced line breaks matching the browser exactly
}

export function emitJsx(scene: Scene, opts: EmitOptions): string {
  const sceneJson = JSON.stringify({ scene, opts: { outDir: opts.outDir, hardLineBreaks: opts.hardLineBreaks } })
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029")
    .replace(/<\/script/gi, "<\\/script")
    .replace(/[\u0080-\uffff]/g, (ch) => "\\u" + ch.charCodeAt(0).toString(16).padStart(4, "0"));

  return `// Generated by indesign-bridge - do not edit by hand.
var PAYLOAD = ${sceneJson};
var SCENE = PAYLOAD.scene;
var OPTS = PAYLOAD.opts;
var LOG = [];
var TEXT_GEOMETRY = [];
var CONTAINER_GEOMETRY = [];

function positionBgContent(frame, bgPos) {
  // CSS background-position for cover/contain crops. Runs right after
  // CENTER_CONTENT, so the graphic is exactly centered: move only by the
  // delta between the desired offset and the centered offset. Pure relative
  // move - immune to page-vs-spread ruler-origin mismatches on recto pages.
  try {
    var g = frame.allGraphics[0];
    if (!g) return;
    var fb = frame.geometricBounds;
    var gb = g.geometricBounds;
    var fw = fb[3] - fb[1], fh = fb[2] - fb[0];
    var gw = gb[3] - gb[1], gh = gb[2] - gb[0];
    var ox = bgPos.xUnit === "%" ? (fw - gw) * bgPos.x / 100 : bgPos.x;
    var oy = bgPos.yUnit === "%" ? (fh - gh) * bgPos.y / 100 : bgPos.y;
    var dx = ox - (fw - gw) / 2;
    var dy = oy - (fh - gh) / 2;
    if (Math.abs(dx) < 0.05 && Math.abs(dy) < 0.05) return;
    g.move(undefined, [dx, dy]);
    log("BGPOS " + frame.name + " dx=" + Math.round(dx*100)/100 + " dy=" + Math.round(dy*100)/100);
  } catch (ePos) { log("BGPOS FAILED: " + ePos.message); }
}

function placeCssFit(frame, box, contain, bgPos, pad) {
  // CSS background-size cover/contain + background-position, computed from
  // the element box (y0, x0, y1, x1) rather than from the frame, which may
  // already be clipped to the page or pasteboard. With pad, the placed file
  // carries mirrored bleed pixels around the original image: fit uses the
  // original aspect, then the graphic grows outward by the padding.
  frame.fit(FitOptions.PROPORTIONALLY); // places the graphic; we only need its aspect
  var g = frame.allGraphics[0];
  if (!g) return;
  var ib = g.geometricBounds;
  var aspect = pad ? pad.natW / pad.natH : (ib[3] - ib[1]) / (ib[2] - ib[0]);
  var ew = box[3] - box[1], eh = box[2] - box[0];
  var widthLed = contain ? (ew / eh < aspect) : (ew / eh > aspect);
  var dw = widthLed ? ew : eh * aspect;
  var dh = widthLed ? ew / aspect : eh;
  var px = 50, pxUnit = "%", py = 50, pyUnit = "%";
  if (bgPos) { px = bgPos.x; pxUnit = bgPos.xUnit; py = bgPos.y; pyUnit = bgPos.yUnit; }
  var x0 = box[1] + (pxUnit === "%" ? (ew - dw) * px / 100 : px);
  var y0 = box[0] + (pyUnit === "%" ? (eh - dh) * py / 100 : py);
  if (pad) {
    var s = dw / pad.natW; // pt per source px
    g.geometricBounds = [y0 - pad.t * s, x0 - pad.l * s, y0 + dh + pad.b * s, x0 + dw + pad.r * s];
    return;
  }
  g.geometricBounds = [y0, x0, y0 + dh, x0 + dw];
}

function log(msg) { LOG.push(msg); }

function writeLog() {
  var f = new File(OPTS.outDir + "/build-result.json");
  f.encoding = "UTF-8";
  f.open("w");
  f.write('{"log":["' + joinEscaped(LOG) + '"],"textGeometry":[' + TEXT_GEOMETRY.join(",") + '],"containerGeometry":[' + CONTAINER_GEOMETRY.join(",") + ']}');
  f.close();
}

function jsonString(value) {
  return '"' + String(value).replace(/\\\\/g, "\\\\\\\\").replace(/"/g, '\\\\"')
    .replace(/\\r/g, "\\\\r").replace(/\\n/g, "\\\\n").replace(/\\t/g, "\\\\t") + '"';
}

function joinEscaped(arr) {
  var out = [];
  for (var i = 0; i < arr.length; i++) {
    out.push(String(arr[i]).replace(/\\\\/g, "\\\\\\\\").replace(/"/g, '\\\\"')
      .replace(/\\r/g, "\\\\r").replace(/\\n/g, "\\\\n").replace(/\\t/g, "\\\\t"));
  }
  return out.join('","');
}

// Weight fallback chains, mirroring how browsers substitute missing faces.
var STYLE_FALLBACKS = {
  "Thin": ["Thin", "UltraLight", "ExtraLight", "Light"],
  "ExtraLight": ["ExtraLight", "UltraLight", "Thin", "Light"],
  "Light": ["Light", "Regular"],
  "Regular": ["Regular", "Roman", "Book", "Normal", "Medium"],
  "Medium": ["Medium", "Regular", "SemiBold"],
  "SemiBold": ["SemiBold", "DemiBold", "Demibold", "Semibold", "Bold", "ExtraBold", "Black", "Medium", "Regular"],
  "Bold": ["Bold", "SemiBold", "Heavy"],
  "ExtraBold": ["ExtraBold", "Heavy", "Black", "Bold"],
  "Black": ["Black", "Heavy", "ExtraBold", "Bold"]
};
var RESOLVED_STYLES = {};

function resolveStyle(family, style) {
  var key = family + "\\t" + style;
  if (RESOLVED_STYLES.hasOwnProperty(key)) return RESOLVED_STYLES[key];
  var italic = style.indexOf("Italic") >= 0;
  var baseStyle = italic ? style.replace(/ ?Italic/, "") : style;
  if (baseStyle === "") baseStyle = "Regular";
  var cands = STYLE_FALLBACKS[baseStyle] || [baseStyle];
  var result = null;
  for (var i = 0; i < cands.length && !result; i++) {
    var names = italic ? [cands[i] + " Italic", cands[i] + " Oblique"] : [cands[i]];
    if (italic && cands[i] === "Regular") names.push("Italic");
    for (var j = 0; j < names.length && !result; j++) {
      var f = app.fonts.itemByName(family + "\\t" + names[j]);
      if (f.isValid && f.status === FontStatus.INSTALLED) result = names[j];
    }
  }
  if (result && result !== style) log("FONT SUBSTITUTED: " + family + " " + style + " -> " + result);
  RESOLVED_STYLES[key] = result;
  return result;
}

var RESOLVED_FONTS = {};

// Exact face lookup by PostScript/full name ("FKScreamer-Bold" -> family "FK
// Screamer Bold", style "Regular"). The map is parsed locally from installed
// font files and shipped inside the scene - never iterate app.fonts, a bulk
// request across thousands of faces hangs InDesign.
function psLookup(name) {
  var hints = SCENE.fontHints || {};
  if (hints.hasOwnProperty(name)) return hints[name];
  return null;
}

// Try each CSS family candidate: family+style chain first, then the raw name
// as a PostScript lookup. Returns {family, style} or null.
function resolveFont(families, style) {
  var key = families.join("|") + "\\t" + style;
  if (RESOLVED_FONTS.hasOwnProperty(key)) return RESOLVED_FONTS[key];
  // PostScript-style names ("SyntheticSans-Semibold", "SyntheticSerif-Regular") pin
  // the exact face. Extract their style tokens and try them against the plain
  // family candidates before any weight-chain guessing.
  var TOKEN_MAP = { "Rg": "Regular", "Reg": "Regular", "Md": "Medium", "Bd": "Bold", "Lt": "Light", "Blk": "Black", "Hv": "Heavy", "It": "Italic", "SemiBold": "Semibold" };
  var styleTokens = [];
  for (var t = 0; t < families.length; t++) {
    var dash = families[t].lastIndexOf("-");
    if (dash > 0) {
      var tok = families[t].slice(dash + 1);
      var variants = [tok];
      if (TOKEN_MAP[tok]) variants.push(TOKEN_MAP[tok]);
      if (tok.toLowerCase() === "semibold") variants = ["Semibold", "SemiBold", "Semi Bold", "DemiBold", "Demibold"];
      for (var tv = 0; tv < variants.length; tv++) styleTokens.push(variants[tv]);
    }
  }
  var result = null;
  for (var i = 0; i < families.length && !result; i++) {
    var fam = families[i];
    var semanticStyle = style.toLowerCase();
    if (semanticStyle === "italic" || semanticStyle === "oblique") semanticStyle = "regular italic";
    var semantic = psLookup(fam + "\t" + semanticStyle);
    if (semantic) {
      result = { family: semantic.family, style: semantic.style };
      log("FONT FACE ALIAS: " + fam + " " + style + " -> " + result.family + " / " + result.style);
      break;
    }
    if (fam.indexOf("-") !== -1) {
      var ps = psLookup(fam);
      if (ps) {
        result = { family: ps.family, style: ps.style };
        break;
      }
      continue; // dash names are faces, not families - no chain guessing
    }
    for (var tk = 0; tk < styleTokens.length && !result; tk++) {
      try {
        var tf2 = app.fonts.itemByName(fam + "\\t" + styleTokens[tk]);
        if (tf2.isValid && tf2.status === FontStatus.INSTALLED) result = { family: fam, style: styleTokens[tk] };
      } catch (e1) {}
    }
    if (!result) {
      var st = resolveStyle(fam, style);
      if (st !== null) result = { family: fam, style: st };
    }
  }
  for (var j = 0; j < families.length && !result; j++) {
    try {
      var f = app.fonts.itemByName(families[j]);
      if (f.isValid && f.status === FontStatus.INSTALLED) result = { family: f.fontFamily, style: f.fontStyleName };
    } catch (e) {}
  }
  if (result) log("FONT: " + families[0] + " " + style + " -> " + result.family + " / " + result.style);
  RESOLVED_FONTS[key] = result;
  return result;
}

function rgbSwatchName(c) { return "RGB " + c.r + "-" + c.g + "-" + c.b; }

function ensureColor(doc, c) {
  var name = rgbSwatchName(c);
  var col = doc.colors.itemByName(name);
  if (!col.isValid) {
    col = doc.colors.add({ name: name, model: ColorModel.PROCESS, space: ColorSpace.RGB, colorValue: [c.r, c.g, c.b] });
    // Parallel CMYK companion swatch (naive conversion; flip per-document when going to press)
    var rr = c.r / 255, gg = c.g / 255, bb = c.b / 255;
    var k = 1 - Math.max(rr, Math.max(gg, bb));
    var cc = 0, mm = 0, yy = 0;
    if (k < 1) {
      cc = (1 - rr - k) / (1 - k);
      mm = (1 - gg - k) / (1 - k);
      yy = (1 - bb - k) / (1 - k);
    }
    var cName = "CMYK of " + name;
    if (!doc.colors.itemByName(cName).isValid) {
      doc.colors.add({ name: cName, model: ColorModel.PROCESS, space: ColorSpace.CMYK,
        colorValue: [Math.round(cc * 100), Math.round(mm * 100), Math.round(yy * 100), Math.round(k * 100)] });
    }
  }
  return doc.colors.itemByName(name);
}

function setCorners(item, radii) {
  if (!radii) return;
  var opts = [
    ["topLeftCornerOption", "topLeftCornerRadius", radii[0]],
    ["topRightCornerOption", "topRightCornerRadius", radii[1]],
    ["bottomRightCornerOption", "bottomRightCornerRadius", radii[2]],
    ["bottomLeftCornerOption", "bottomLeftCornerRadius", radii[3]]
  ];
  for (var i = 0; i < opts.length; i++) {
    if (opts[i][2] > 0.01) {
      item[opts[i][0]] = CornerOptions.ROUNDED_CORNER;
      item[opts[i][1]] = opts[i][2];
    }
  }
}

function setOpacity(item, o) {
  if (o < 0.999) item.transparencySettings.blendingSettings.opacity = o * 100;
}

var GROUP_MAP = {};
function regGroup(n, item) {
  if (!n.rotGroup) return;
  if (!GROUP_MAP[n.rotGroup]) GROUP_MAP[n.rotGroup] = [];
  GROUP_MAP[n.rotGroup].push(item);
}

function rotateCenter(item, deg) {
  if (Math.abs(deg) < 0.01) return;
  item.transform(CoordinateSpaces.PASTEBOARD_COORDINATES, AnchorPoint.CENTER_ANCHOR,
    app.transformationMatrices.add({ counterclockwiseRotationAngle: -deg }));
}

// Rotate as if around the CSS pivot (ex,ey) when the item's own center
// (fx,fy) differs - CSS transform-origin is often a corner, and text frames
// carry asymmetric slack so their center is not the element center.
function rotateAdjusted(item, deg, ex, ey, fx, fy) {
  if (Math.abs(deg) < 0.01) return;
  rotateCenter(item, deg);
  var th = deg * Math.PI / 180;
  var vx = ex - fx, vy = ey - fy;
  var dx = (1 - Math.cos(th)) * vx + Math.sin(th) * vy;
  var dy = -Math.sin(th) * vx + (1 - Math.cos(th)) * vy;
  if (Math.abs(dx) > 0.01 || Math.abs(dy) > 0.01) item.move(undefined, [dx, dy]);
}

// Rotate a node's item honoring CSS transform-origin (element-relative).
function rotateNode(item, n, itemCx, itemCy) {
  if (Math.abs(n.rotationDeg) < 0.01) return;
  var px = n.x + (n.rotOrigin ? n.rotOrigin.x : n.width / 2);
  var py = n.y + (n.rotOrigin ? n.rotOrigin.y : n.height / 2);
  rotateAdjusted(item, n.rotationDeg, px, py, itemCx, itemCy);
}

function main() {
  app.scriptPreferences.userInteractionLevel = UserInteractionLevels.NEVER_INTERACT;
  app.scriptPreferences.measurementUnit = MeasurementUnits.POINTS;

  // Font availability report (resolveStyle logs substitutions as a side effect)
  for (var fi = 0; fi < SCENE.fonts.length; fi++) {
    var fnt = SCENE.fonts[fi];
    if (resolveFont(fnt.families, fnt.style) === null) {
      log("MISSING FONT: " + fnt.families.join(" / ") + " " + fnt.style);
    }
  }

  var PRESET = SCENE.printPreset || null;
  var first = SCENE.pages[0];
  var doc;
  var TOTAL_PAGES;
  if (PRESET) {
    TOTAL_PAGES = 0;
    for (var tc = 0; tc < SCENE.pages.length; tc++) {
      if ((SCENE.pages[tc].spreadRole || "spread") === "spread") {
        if ((TOTAL_PAGES + 1) % 2 === 1) TOTAL_PAGES++; // blank so the spread starts verso
        TOTAL_PAGES += 2;
      } else {
        TOTAL_PAGES++;
      }
    }
    doc = app.documents.add({
      documentPreferences: {
        pageWidth: PRESET.pageWidth + "pt",
        pageHeight: PRESET.pageHeight + "pt",
        pagesPerDocument: TOTAL_PAGES,
        facingPages: true,
        intent: DocumentIntentOptions.PRINT_INTENT,
        documentBleedTopOffset: PRESET.bleed, documentBleedBottomOffset: PRESET.bleed,
        documentBleedInsideOrLeftOffset: PRESET.bleed, documentBleedOutsideOrRightOffset: PRESET.bleed
      }
    });
  } else {
    TOTAL_PAGES = SCENE.pages.length;
    doc = app.documents.add({
      documentPreferences: {
        pageWidth: first.widthPx + "pt",
        pageHeight: first.heightPx + "pt",
        pagesPerDocument: SCENE.pages.length,
        facingPages: false,
        documentBleedTopOffset: 0, documentBleedBottomOffset: 0,
        documentBleedInsideOrLeftOffset: 0, documentBleedOutsideOrRightOffset: 0
      }
    });
  }
  doc.viewPreferences.horizontalMeasurementUnits = MeasurementUnits.POINTS;
  doc.viewPreferences.verticalMeasurementUnits = MeasurementUnits.POINTS;
  doc.viewPreferences.rulerOrigin = RulerOrigin.PAGE_ORIGIN;
  // Design-faithful transparency: blend in RGB like the browser; CMYK
  // conversion belongs to the output/prepress step.
  try { doc.transparencyPreference.blendingSpace = BlendingSpace.RGB; }
  catch (eT1) { try { doc.transparencyPreferences.blendingSpace = BlendingSpace.RGB; } catch (eT2) {} }
  // Browser designs are sRGB. If the document inherits the host's RGB working
  // space (Adobe RGB on print setups) every export writes Adobe RGB numbers
  // that viewers read as sRGB: saturated colours can dull. Pin the document
  // profile so output numbers match the source color space.
  try { doc.rgbPolicy = ColorSettingsPolicy.PRESERVE_EMBEDDED_PROFILES; } catch (eRP) {}
  try { doc.rgbProfile = "sRGB IEC61966-2.1"; log("RGB profile: " + doc.rgbProfile); }
  catch (eRGB) { log("RGB PROFILE FAILED: " + eRGB.message); }

  // Build with a roomy pasteboard (rotations pass through wide intermediate
  // geometry); print mode snugs it down just before save.
  try { doc.pasteboardPreferences.pasteboardMargins = ["2000pt", "2000pt"]; } catch (ePb) {}

  // Print mode: template margins/columns on every page + semantic layers.
  var LAYER_BG = null, LAYER_GFX = null, LAYER_TEXT = null;
  var LAYER_CONTAINERS = doc.layers.add({ name: "SOURCE CONTAINERS" });
  try { LAYER_CONTAINERS.printable = false; } catch (eLayerPrint) {}
  if (PRESET) {
    for (var mpi = 0; mpi < doc.pages.length; mpi++) {
      doc.pages.item(mpi).marginPreferences.properties = {
        top: PRESET.margins.top, bottom: PRESET.margins.bottom,
        left: PRESET.margins.left, right: PRESET.margins.right,
        columnCount: PRESET.margins.columns
      };
    }
    // IMAGES = page backgrounds + every placed image (photography, svg
    // rasters) so photos are one navigable group in the Layers panel.
    LAYER_BG = doc.layers.add({ name: "IMAGES" });
    LAYER_GFX = doc.layers.add({ name: "GRAPHIC ELEMENTS" });
    LAYER_TEXT = doc.layers.add({ name: "TEXT" });
    // Drop the empty default layer so the panel is just the semantic three.
    try {
      var defL = doc.layers.itemByName("Layer 1");
      if (defL.isValid && defL.pageItems.length === 0) defL.remove();
    } catch (eDefL) {}
  }

  // Compute bleed-extended bounds WITHOUT moving the node - images are fitted
  // at trim (design-exact, no zoom), then their frame grows into the bleed.
  function extendBleed(n, boardW, boardH) {
    if (!PRESET) return;
    if (n.kind !== "rect" && n.kind !== "image") return;
    var b = PRESET.bleed;
    var x0 = n.x, y0 = n.y, x1 = n.x + n.width, y1 = n.y + n.height;
    var ext = false;
    if (y0 <= 0.75) { y0 = -b; ext = true; }
    if (y1 >= boardH - 0.75) { y1 = boardH + b; ext = true; }
    if (x0 <= 0.75) { x0 = -b; ext = true; }
    if (x1 >= boardW - 0.75) { x1 = boardW + b; ext = true; }
    // A page alone in its spread (front/back cover) is trimmed on its spine
    // side too, so art reaching the content half's inner edge bleeds there.
    if (aloneInSpread && singlePage !== null) {
      var half = boardW / 2;
      if (role === "left" && x1 >= half - 0.75 && x0 < half) { x1 = half + b; ext = true; }
      if (role === "right" && x0 <= half + 0.75 && x1 > half) { x0 = half - b; ext = true; }
    }
    if (ext) n.bleedExt = { x0: x0, y0: y0, x1: x1, y1: y1 };
  }

  var PAGE_CURSOR = 0;
  for (var p = 0; p < SCENE.pages.length; p++) {
    var sp = SCENE.pages[p];
    var page = null, layer = null, leftPage = null, rightPage = null;
    var role = sp.spreadRole || "spread";
    var isCover = PRESET !== null && role === "right";
    var isBack = PRESET !== null && role === "left";

    var singlePage = null, aloneInSpread = false;
    if (PRESET) {
      log("BOARD '" + sp.name + "' -> " + role + " (page " + (PAGE_CURSOR + 1) + (role === "spread" ? "-" + (PAGE_CURSOR + 2) : "") + ")");
      if (role !== "spread") {
        // A single-page board flows onto the next page, whichever side it is.
        singlePage = doc.pages.item(PAGE_CURSOR); PAGE_CURSOR += 1;
        // A cover or back cover sits alone in its spread: it has no facing
        // page to protect, so its inside (spine) edge bleeds like the others.
        aloneInSpread = singlePage.parent.pages.length === 1;
      } else {
        if ((PAGE_CURSOR + 1) % 2 === 1) {
          log("BLANK page " + (PAGE_CURSOR + 1) + " inserted so spread '" + sp.name + "' starts on a verso.");
          PAGE_CURSOR += 1;
        }
        leftPage = doc.pages.item(PAGE_CURSOR); rightPage = doc.pages.item(PAGE_CURSOR + 1); PAGE_CURSOR += 2;
      }
    } else {
      page = doc.pages.item(p);
      var pg = sp.pageGuides || { top: 0, left: 0, bottom: 0, right: 0, columns: 1, columnGutter: 0 };
      page.marginPreferences.properties = {
        top: pg.top, left: pg.left, bottom: pg.bottom, right: pg.right,
        columnCount: pg.columns || 1, columnGutter: pg.columnGutter || 0
      };
      if (Math.abs(sp.widthPx - first.widthPx) > 0.1 || Math.abs(sp.heightPx - first.heightPx) > 0.1) {
        page.resize(CoordinateSpaces.INNER_COORDINATES, AnchorPoint.TOP_LEFT_ANCHOR,
          ResizeMethods.REPLACING_CURRENT_DIMENSIONS_WITH, [sp.widthPx, sp.heightPx]);
      }
      var layerName = "Page " + (p + 1) + " - " + sp.name;
      layer = doc.layers.itemByName(layerName);
      if (!layer.isValid) layer = doc.layers.add({ name: layerName });
    }

    // Route a node to its page (mutates n.x for right-half placement) + layer.
    var shiftNode = function (n) {
      n.x -= PRESET.pageWidth;
      if (n.bleedExt) { n.bleedExt.x0 -= PRESET.pageWidth; n.bleedExt.x1 -= PRESET.pageWidth; }
      if (n.clip) n.clip.x -= PRESET.pageWidth;
      if (n.rotOrigin) { /* element-relative, no shift */ }
      if (n.visualLines) {
        for (var vlS = 0; vlS < n.visualLines.length; vlS++) n.visualLines[vlS].x -= PRESET.pageWidth;
      }
      if (n.runs) {
        for (var rS = 0; rS < n.runs.length; rS++) {
          for (var lS = 0; lS < n.runs[rS].lines.length; lS++) n.runs[rS].lines[lS].x -= PRESET.pageWidth;
        }
      }
    };
    var pageForNode = function (n) {
      if (!PRESET) return page;
      if (singlePage !== null) {
        if (role === "right") shiftNode(n);
        return singlePage;
      }
      // Only nodes FULLY right of the spine move to the recto (safe, probe A).
      // Spine-crossers stay on the verso in spread coordinates (safe, probe C);
      // right-page bounds that cross the spine get misplaced by InDesign.
      if (rightPage !== null && n.x >= PRESET.pageWidth - 1) { shiftNode(n); return rightPage; }
      return leftPage;
    };
    var layerForNode = function (n) {
      if (n.kind === "container") return LAYER_CONTAINERS;
      if (!PRESET) return layer;
      if (n.layerHint === "BG") return LAYER_BG;
      if (n.layerHint === "TEXT") return LAYER_TEXT;
      if (n.kind === "image") return LAYER_BG;
      return LAYER_GFX;
    };
    var sprRef = (page !== null ? page : (singlePage !== null ? singlePage : leftPage)).parent;

    // Page background
    if (sp.background) {
      var bgN = { kind: "rect", name: "Background", x: 0, y: 0, width: sp.widthPx, height: sp.heightPx };
      extendBleed(bgN, sp.widthPx, sp.heightPx);
      var bgPage = PRESET ? pageForNode(bgN) : page;
      var bgLayer = PRESET ? LAYER_BG : layer;
      // Spread backgrounds run into the bleed on every outer edge; stopping at
      // trim left a white hairline risk on every solid-colour page.
      var bgGB = [bgN.y, bgN.x, bgN.y + bgN.height, bgN.x + bgN.width];
      if (PRESET && singlePage === null && bgN.bleedExt) {
        bgGB = [bgN.bleedExt.y0, bgN.bleedExt.x0, bgN.bleedExt.y1, bgN.bleedExt.x1];
      }
      var bgRect = bgPage.rectangles.add(bgLayer, {
        geometricBounds: bgGB,
        fillColor: ensureColor(doc, sp.background),
        strokeColor: doc.swatches.itemByName("None"), strokeWeight: 0, name: "Background"
      });
      bgRect.textWrapPreferences.textWrapMode = TextWrapModes.NONE;
    }

    var CONTAINER_ITEMS = [];
    for (var i = 0; i < sp.nodes.length; i++) {
      var n = sp.nodes[i];
      // Cull nodes entirely outside the page plus a margin - they are
      // invisible in the design and would fall off the pasteboard.
      // Anything fully outside the frame (+bleed) is invisible - drop it.
      var cullM = PRESET ? 12 : 1500;
      if (n.x > sp.widthPx + cullM || n.y > sp.heightPx + cullM ||
          n.x + n.width < -cullM || n.y + n.height < -cullM) {
        log("SKIPPED off-canvas node '" + n.name + "' at " + Math.round(n.x) + "," + Math.round(n.y));
        continue;
      }
      extendBleed(n, sp.widthPx, sp.heightPx);
      // Single-page boards: clip to the content half so nothing invades the
      // neighboring page across the fold (outer edges keep their bleed).
      if (PRESET && singlePage !== null) {
        var loB = role === "right" ? PRESET.pageWidth - (aloneInSpread ? PRESET.bleed : 0) : -PRESET.bleed;
        var hiB = role === "right" ? sp.widthPx + PRESET.bleed : PRESET.pageWidth + (aloneInSpread ? PRESET.bleed : 0);
        if (n.x + n.width <= loB + 0.5 || n.x >= hiB - 0.5) {
          log("SKIPPED off-half node '" + n.name + "' on single board '" + sp.name + "'");
          continue;
        }
        // Images keep their full CSS box here: cover/contain fitting must be
        // computed against the element as Chrome laid it out, or the crop
        // re-centres on the clipped half. They are cropped at the fold after
        // fitting instead (see "crop art at the fold" below).
        if (n.kind === "rect") {
          if (n.x < loB) { n.width -= loB - n.x; n.x = loB; }
          if (n.x + n.width > hiB) { n.width = hiB - n.x; }
          if (n.bleedExt) {
            n.bleedExt.x0 = Math.max(n.bleedExt.x0, loB);
            n.bleedExt.x1 = Math.min(n.bleedExt.x1, hiB);
          }
        }
      }
      var tgtPage = pageForNode(n);
      var tgtLayer = layerForNode(n);
      var gb = [n.y, n.x, n.y + n.height, n.x + n.width];
      // The element's own box, before any pasteboard or fold clamping. CSS
      // cover/contain crops are defined against this, not the clipped frame.
      var elemBox = gb.slice(0);
      // Spread-aware pasteboard envelope: the facing page is canvas, not
      // pasteboard, so frames may span the full spread plus margins.
      var loX = -150, hiX = PRESET ? PRESET.pageWidth + 150 : 0;
      if (PRESET && singlePage === null) {
        if (tgtPage === rightPage) loX = -PRESET.pageWidth - 150;
        else hiX = 2 * PRESET.pageWidth + 150;
      }
      if (PRESET && Math.abs(n.rotationDeg) < 0.01) {
        // Rotated nodes skip this: their unrotated intermediate geometry is
        // wide, but their final position lands on the page.
        var preH = gb[2] - gb[0], preW = gb[3] - gb[1];
        gb[0] = Math.max(gb[0], -88); gb[1] = Math.max(gb[1], loX);
        gb[2] = Math.min(gb[2], PRESET.pageHeight + 88); gb[3] = Math.min(gb[3], hiX);
        // Skip only nodes the clamp actually collapsed to a sliver - a node
        // that was hairline-thin to begin with (1px dividers) is legitimate.
        if ((gb[2] <= gb[0] + 1 && preH > 1) || (gb[3] <= gb[1] + 1 && preW > 1) ||
            gb[2] <= gb[0] || gb[3] <= gb[1]) {
          log("SKIPPED pasteboard-clamped-away node '" + n.name + "'");
          continue;
        }
      }
      try {
        if (n.kind === "container") {
          var sourceFrame = tgtPage.rectangles.add(tgtLayer, {
            geometricBounds: gb,
            name: "[" + n.sourceType + "] " + n.name,
            fillColor: doc.swatches.itemByName("None"),
            strokeColor: doc.swatches.itemByName("None"),
            strokeWeight: 0
          });
          sourceFrame.label = "figma-source:" + n.sourceId + ";parent:" + (n.sourceParentId || "") + ";depth:" + n.sourceDepth + ";clips:" + (n.clipsContent ? "true" : "false");
          try { sourceFrame.nonprinting = true; } catch (eNonPrint) {}
          sourceFrame.textWrapPreferences.textWrapMode = TextWrapModes.NONE;
          var sourceBounds = sourceFrame.geometricBounds;
          CONTAINER_GEOMETRY.push('{"page":' + (p + 1) +
            ',"node":' + jsonString(n.sourceId) +
            ',"sourceType":' + jsonString(n.sourceType) +
            ',"expectedBounds":[' + [n.y, n.x, n.y + n.height, n.x + n.width].join(",") + ']' +
            ',"actualBounds":[' + [Number(sourceBounds[0]), Number(sourceBounds[1]), Number(sourceBounds[2]), Number(sourceBounds[3])].join(",") + ']' +
            ',"measurable":true}');
          CONTAINER_ITEMS.push(sourceFrame);
        } else if (n.kind === "rect") {
          // Solid fills take the bleed-extended bounds directly.
          if (n.bleedExt) {
            gb = [Math.max(n.bleedExt.y0, -88), Math.max(n.bleedExt.x0, loX),
                  Math.min(n.bleedExt.y1, PRESET.pageHeight + 88), Math.min(n.bleedExt.x1, hiX)];
          }
          var rect = tgtPage.rectangles.add(tgtLayer, {
            geometricBounds: gb, name: n.name,
            fillColor: n.fill ? ensureColor(doc, n.fill) : doc.swatches.itemByName("None"),
            strokeColor: n.strokeColor ? ensureColor(doc, n.strokeColor) : doc.swatches.itemByName("None"),
            strokeWeight: n.strokeWeightPx
          });
          if (n.strokeWeightPx > 0) rect.strokeAlignment = StrokeAlignment.INSIDE_ALIGNMENT;
          setCorners(rect, n.cornerRadius);
          if (n.shadow) {
            var ds = rect.transparencySettings.dropShadowSettings;
            ds.mode = ShadowMode.DROP;
            ds.xOffset = n.shadow.x;
            ds.yOffset = n.shadow.y;
            ds.size = Math.max(0, n.shadow.blur + Math.max(0, n.shadow.spread));
            ds.opacity = Math.min(100, n.shadow.alpha * 100);
            ds.effectColor = ensureColor(doc, n.shadow.color);
          }
          setOpacity(rect, n.opacity);
          rotateNode(rect, n, n.x + n.width / 2, n.y + n.height / 2);
          regGroup(n, rect);
        } else if (n.kind === "image" || n.kind === "svg") {
          var frame = tgtPage.rectangles.add(tgtLayer, {
            geometricBounds: gb, name: n.name,
            fillColor: doc.swatches.itemByName("None"),
            strokeColor: doc.swatches.itemByName("None"), strokeWeight: 0
          });
          setCorners(frame, n.cornerRadius);
          var srcName = n.src;
          if (n.kind === "svg" && n.preferRaster && n.fallbackPng) srcName = n.fallbackPng;
          var imgFile = new File(OPTS.outDir + "/Links/" + srcName);
          if (imgFile.exists) {
            var placed = false;
            try {
              frame.place(imgFile);
              placed = true;
            } catch (placeErr) {
              if (n.kind === "svg" && n.fallbackPng) {
                var pngFile = new File(OPTS.outDir + "/Links/" + n.fallbackPng);
                if (pngFile.exists) {
                  frame.place(pngFile);
                  placed = true;
                  log("SVG RASTER FALLBACK: '" + n.name + "' placed as " + n.fallbackPng);
                }
              }
              if (!placed) throw placeErr;
            }
            if (n.kind === "svg" || n.fit === "fill") {
              frame.fit(FitOptions.CONTENT_TO_FRAME);
            } else if (Math.abs(n.rotationDeg) < 0.01) {
              // Deterministic CSS fit: size and place the graphic against the
              // element's unclipped box, so pasteboard/fold clamping of the
              // frame can never shift the crop.
              // Edge images arrive pre-padded with mirrored pixels (bleed-pad.ts),
              // so they fill the bleed at the design's exact scale and crop.
              placeCssFit(frame, elemBox, n.fit === "contain", n.bgPos, n.bleedPad);
            } else if (n.fit === "contain") {
              frame.fit(FitOptions.PROPORTIONALLY);
              frame.fit(FitOptions.CENTER_CONTENT);
              if (n.bgPos) positionBgContent(frame, n.bgPos);
            } else {
              frame.fit(FitOptions.FILL_PROPORTIONALLY);
              frame.fit(FitOptions.CENTER_CONTENT);
              if (n.bgPos) positionBgContent(frame, n.bgPos);
            }
            // Untagged images take the document profile, now pinned to sRGB
            // (as browsers assume). Images with their own ICC profile must
            // keep it: Chrome honours embedded Adobe RGB, and overriding it to
            // sRGB reinterprets the numbers and dulls saturated colour.
            try {
              var gph0 = frame.allGraphics[0];
              if (gph0) log("IMAGE PROFILE '" + n.name + "': " + gph0.profile);
            } catch (eProf) {}

            // Grow the frame into the bleed AFTER fitting - the design-exact
            // crop is preserved; the bleed shows real spare image where the
            // cover-crop has overflow, and stays empty elsewhere.
            if (n.bleedExt) {
              try {
                frame.geometricBounds = [Math.max(n.bleedExt.y0, -88), Math.max(n.bleedExt.x0, loX),
                  Math.min(n.bleedExt.y1, PRESET.pageHeight + 88), Math.min(n.bleedExt.x1, hiX)];
              } catch (eBE) { log("BLEED EXTEND FAILED on '" + n.name + "': " + eBE.message); }
            }
            // Single-page boards: crop art at the fold (content stays put) so
            // parts hidden by the other half's panels never leak onto the page.
            if (PRESET && singlePage !== null && Math.abs(n.rotationDeg) < 0.01) {
              var cLo = role === "right" ? (aloneInSpread ? -PRESET.bleed : 0) : -PRESET.bleed;
              var cHi = role === "right" ? PRESET.pageWidth + PRESET.bleed : PRESET.pageWidth + (aloneInSpread ? PRESET.bleed : 0);
              try {
                var fgb = frame.geometricBounds;
                if (fgb[1] < cLo - 0.1 || fgb[3] > cHi + 0.1) {
                  frame.geometricBounds = [fgb[0], Math.max(fgb[1], cLo), fgb[2], Math.min(fgb[3], cHi)];
                }
              } catch (eFC) {}
            }
            // Crop to an overflow-clipping ancestor (Paper's crop frame). The
            // graphic stays placed against the element box; only the frame
            // shrinks, so this runs last and wins over bleed extension.
            if (n.clip) {
              try {
                var cgb = frame.geometricBounds;
                var nb0 = Math.max(cgb[0], n.clip.y), nb1 = Math.max(cgb[1], n.clip.x);
                var nb2 = Math.min(cgb[2], n.clip.y + n.clip.height), nb3 = Math.min(cgb[3], n.clip.x + n.clip.width);
                if (nb2 > nb0 && nb3 > nb1) frame.geometricBounds = [nb0, nb1, nb2, nb3];
                log("CLIP '" + n.name + "' to crop frame");
              } catch (eClip) { log("CLIP FAILED on '" + n.name + "': " + eClip.message); }
            }
          } else {
            log("MISSING LINK: " + n.src);
          }
          setOpacity(frame, n.opacity);
          rotateNode(frame, n, n.x + n.width / 2, n.y + n.height / 2);
          regGroup(n, frame);
        } else if (n.kind === "text") {
          // First-line hang (display headlines): indent line 1 only. Other
          // stagger patterns are logged, not guessed.
          var firstLineInd = 0;
          if (OPTS.hardLineBreaks && n.visualLines && n.visualLines.length >= 2 && n.align === "left") {
            var ind0 = n.visualLines[0].x - n.x;
            var restMax = 0;
            for (var sg = 1; sg < n.visualLines.length; sg++) {
              var sgi = n.visualLines[sg].x - n.x;
              if (sgi > restMax) restMax = sgi;
            }
            if (ind0 > 4 && restMax <= 4) firstLineInd = ind0;
            else if (restMax > 4) log("STAGGER UNSUPPORTED on '" + n.name + "' (mid-line indents " + Math.round(restMax) + "pt)");
          }
          // Extra frame slack is safe: fixed first baseline + fixed leading pin
          // every line's position; the slack only prevents overset clipping.
          var maxLeading = 0;
          for (var mr = 0; mr < n.runs.length; mr++) {
            if (n.runs[mr].lineHeightPx > maxLeading) maxLeading = n.runs[mr].lineHeightPx;
          }
          // Width slack absorbs sub-pixel glyph-metric drift so hard-broken
          // lines never re-wrap. It extends AWAY from the alignment anchor,
          // so the anchored edge (and centering) stays exact.
          var maxFs = 0;
          for (var mf = 0; mf < n.runs.length; mf++) {
            if (n.runs[mf].fontSizePx > maxFs) maxFs = n.runs[mf].fontSizePx;
          }
          // Display faces can need up to ~0.45em beyond composed width (ink
          // overhang + trailing tracking) before a lone word stops oversetting.
          var slack = Math.max(8, n.width * 0.02, maxFs * 1.0);
          var tfx1 = n.x, tfx2 = n.x + n.width;
          var oneLinePin = OPTS.hardLineBreaks && n.visualLines && n.visualLines.length === 1;
          if (oneLinePin) {
            // Single lines: left-anchor the frame at the MEASURED line origin -
            // InDesign's composed width can no longer shift the glyphs.
            tfx1 = n.visualLines[0].x;
            tfx2 = tfx1 + n.width + slack;
          } else if (n.align === "center") { tfx1 -= slack / 2; tfx2 += slack / 2; }
          else if (n.align === "right") { tfx1 -= slack; }
          else if (n.align === "justify") { tfx2 += 2; }
          else { tfx2 += slack; }
          var tfTop = n.y;
          var rotPinIndent = 0;
          var tfBottom = n.y + n.height + maxLeading * 2 + 16;
          if (Math.abs(n.rotationDeg) > 0.01) {
            // Symmetric frame for rotated text: the frame center coincides
            // with the element center, so center rotation IS the CSS pivot.
            var svH = (maxLeading * 2 + 16) / 2;
            tfTop = n.y - svH;
            tfBottom = n.y + n.height + svH;
            var svW = slack / 2;
            tfx1 = n.x - svW;
            tfx2 = n.x + n.width + svW;
            // Left-aligned glyphs follow the frame edge - restore the measured
            // line origin with an indent (frame center stays the CSS pivot).
            if (oneLinePin) rotPinIndent = n.visualLines[0].x - tfx1;
          }
          if (PRESET) {
            tfx1 = Math.max(tfx1, loX);
            tfx2 = Math.min(tfx2, hiX);
            tfBottom = Math.min(tfBottom, PRESET.pageHeight + 88);
          }
          var tf = tgtPage.textFrames.add(tgtLayer, {
            geometricBounds: [tfTop, tfx1, tfBottom, tfx2],
            name: n.name,
            strokeColor: doc.swatches.itemByName("None"), strokeWeight: 0
          });
          tf.textFramePreferences.properties = {
            insetSpacing: [0, 0, 0, 0],
            verticalJustification: VerticalJustification.TOP_ALIGN,
            firstBaselineOffset: FirstBaseline.FIXED_HEIGHT,
            minimumFirstBaselineOffset: n.firstBaselineY - tfTop,
            ignoreWrap: true
          };

          var contents = "";
          var ranges = [];
          var lineRanges = [];
          if (OPTS.hardLineBreaks && n.visualLines && n.visualLines.length > 0) {
            // Rebuild the browser's exact visual lines: each line is styled
            // segments in order; leading is set per line from baseline deltas.
            var SEP = "\\n";
            for (var vk = 0; vk < n.visualLines.length; vk++) {
              var vl = n.visualLines[vk];
              var lineStart = contents.length;
              for (var sk = 0; sk < vl.segments.length; sk++) {
                var seg = vl.segments[sk];
                ranges.push({ start: contents.length, end: contents.length + seg.text.length, run: n.runs[seg.runIndex] });
                contents += seg.text;
              }
              lineRanges.push({ start: lineStart, end: contents.length, baselineY: vl.baselineY });
              if (vk < n.visualLines.length - 1) {
                contents += SEP;
                // The break character belongs to this line: fold it into the
                // trailing segment's range (and the line range) so it takes the
                // run's pointSize/leading. Left unstyled it stays at the 12pt
                // AUTO default, and the line's effective leading becomes
                // max(run leading, 14.4) - middle lines of 3+ line stacks
                // drifted apart while first/last lines measured correct.
                if (ranges.length) ranges[ranges.length - 1].end += 1;
                lineRanges[lineRanges.length - 1].end += 1;
              }
            }
          } else {
            for (var r = 0; r < n.runs.length; r++) {
              var run = n.runs[r];
              var txt = run.text.replace(/\\n/g, " ");
              ranges.push({ start: contents.length, end: contents.length + txt.length, run: run });
              contents += txt;
            }
          }
          tf.contents = contents;

          var story = tf.parentStory;
          for (var r2 = 0; r2 < ranges.length; r2++) {
            var rg = ranges[r2];
            if (rg.end <= rg.start) continue;
            var chars = story.characters.itemByRange(rg.start, rg.end - 1);
            var tracking = rg.run.fontSizePx > 0 ? (rg.run.letterSpacingPx / rg.run.fontSizePx) * 1000 : 0;
            var resolved = resolveFont(rg.run.fontFamilies, rg.run.fontStyle) ||
              { family: rg.run.fontFamily, style: rg.run.fontStyle };
            chars.properties = {
              pointSize: rg.run.fontSizePx,
              leading: rg.run.lineHeightPx,
              tracking: tracking,
              fillColor: ensureColor(doc, rg.run.color)
            };
            if (rg.run.textTransform === "uppercase") {
              try { chars.capitalization = Capitalization.ALL_CAPS; } catch (eCap) {}
            }
            // Assign the font as an object - a bulk string assignment can be
            // silently dropped, leaving Minion in place.
            var fontObj = app.fonts.itemByName(resolved.family + "\\t" + resolved.style);
            if (fontObj.isValid) {
              chars.appliedFont = fontObj;
            } else {
              log("FONT NOT DIRECTLY ADDRESSABLE: " + resolved.family + "/" + resolved.style + " - using name assignment");
              chars.appliedFont = resolved.family;
              chars.fontStyle = resolved.style;
            }
          }

          // Text colour alpha. InDesign swatches carry no
          // alpha and characters have no opacity, so a uniform alpha becomes
          // the frame's Text transparency; fills and strokes are untouched.
          var textAlpha = 1, mixedAlpha = false;
          for (var ra = 0; ra < ranges.length; ra++) {
            // measure.ts records the colour's alpha as run.opacity.
            var a = ranges[ra].run.opacity !== undefined ? ranges[ra].run.opacity : 1;
            if (ra === 0) textAlpha = a; else if (Math.abs(a - textAlpha) > 0.01) mixedAlpha = true;
          }
          if (mixedAlpha) log("TEXT ALPHA MIXED in " + (n.name || "text") + " - using " + textAlpha);
          if (textAlpha < 0.999) {
            try { tf.contentTransparencySettings.blendingSettings.opacity = textAlpha * 100; }
            catch (eTa) { setOpacity(tf, textAlpha); }
          }

          // Exact vertical placement: leading of line k = baseline delta k-1 -> k.
          for (var lk = 1; lk < lineRanges.length; lk++) {
            if (lineRanges[lk].end > lineRanges[lk].start) {
              var ld = lineRanges[lk].baselineY - lineRanges[lk - 1].baselineY;
              if (ld < 1) ld = 1;
              if (ld > 5000) ld = 5000;
              story.characters.itemByRange(lineRanges[lk].start, lineRanges[lk].end - 1).leading = ld;
            }
          }

          var just = Justification.LEFT_ALIGN;
          if (oneLinePin) { /* pinned single lines are always left-anchored */ }
          else if (n.align === "center") just = Justification.CENTER_ALIGN;
          else if (n.align === "right") just = Justification.RIGHT_ALIGN;
          else if (n.align === "justify") just = Justification.LEFT_JUSTIFIED;
          story.paragraphs.everyItem().properties = { justification: just, hyphenation: false, spaceBefore: 0, spaceAfter: 0 };
          if (firstLineInd > 0) {
            try { story.paragraphs.item(0).firstLineIndent = firstLineInd; } catch (eInd) {}
          }
          if (rotPinIndent > 0.1) {
            try { story.paragraphs.item(0).leftIndent = rotPinIndent; } catch (eRPI) {}
          }

          // Machine-readable source-vs-InDesign text geometry. Measurement
          // happens before rotateNode(), so both source and InDesign values
          // are expressed on the same unrotated local baseline axis.
          for (var gm = 0; gm < lineRanges.length; gm++) {
            var srcLine = n.visualLines && n.visualLines[gm] ? n.visualLines[gm] : null;
            var idLine = gm < story.lines.length ? story.lines.item(gm) : null;
            var measurable = srcLine !== null && idLine !== null && idLine.isValid;
            var ax = measurable ? Number(idLine.horizontalOffset) : 0;
            var ab = measurable ? Number(idLine.baseline) : 0;
            TEXT_GEOMETRY.push('{"page":' + (p + 1) +
              ',"node":' + jsonString(n.id || n.name) +
              ',"line":' + (gm + 1) +
              ',"expectedX":' + (srcLine ? Number(srcLine.x) : 0) +
              ',"expectedBaseline":' + Number(lineRanges[gm].baselineY) +
              ',"actualX":' + ax + ',"actualBaseline":' + ab +
              ',"measurable":' + (measurable ? 'true' : 'false') +
              (measurable ? '' : ',"reason":' + jsonString('InDesign did not expose the composed line')) + '}');
          }

          if (tf.overflows) {
            var dbg = "gb=" + tf.geometricBounds.join(",") + " chars=" + story.characters.length + " lines=" + tf.lines.length + " slack=" + slack +
              " rot=" + n.rotationDeg + " fli=" + firstLineInd + " vls=" + (n.visualLines ? n.visualLines.length : -1) + " paras=" + story.paragraphs.length +
              " fbOff=" + Math.round((n.firstBaselineY - n.y) * 10) / 10 + " nH=" + Math.round(n.height * 10) / 10;
            try { dbg += " font=" + story.characters.item(0).appliedFont.name.replace("\\t", "/") + " size=" + story.characters.item(0).pointSize; } catch (eD) {}
            log("OVERSET TEXT: '" + n.name + "' on page " + (p + 1) + " [" + contents.slice(0, 40).replace(/\\n/g, "|") + "] " + dbg);
          }
          // Tidy: shrink the overset slack back to the measured text extents so
          // frames read tight on the canvas. Composition is final here; any
          // shrink that would overset is reverted wholesale.
          if (Math.abs(n.rotationDeg) < 0.01 && !tf.overflows) {
            try {
              var minL = 1e9, maxR = -1e9;
              for (var tr = 0; tr < n.runs.length; tr++) {
                var rls = n.runs[tr].lines;
                for (var tl = 0; tl < rls.length; tl++) {
                  if (rls[tl].x < minL) minL = rls[tl].x;
                  if (rls[tl].x + rls[tl].width > maxR) maxR = rls[tl].x + rls[tl].width;
                }
              }
              var lastBl2 = lineRanges.length ? lineRanges[lineRanges.length - 1].baselineY : (n.y + n.height);
              var padV = maxFs * 0.35 + 1;
              var gbT = tf.geometricBounds;
              var nl = gbT[1], nb = Math.min(gbT[2], lastBl2 + padV), nr = gbT[3];
              if (minL < maxR) {
                if (oneLinePin || n.align === "left" || !n.align) {
                  nr = Math.min(gbT[3], maxR + 1);
                } else if (n.align === "right") {
                  nl = Math.max(gbT[1], minL - 1);
                } else if (n.align === "center") {
                  var ctrim = Math.min(minL - gbT[1], gbT[3] - maxR) - 1;
                  if (ctrim > 0) { nl = gbT[1] + ctrim; nr = gbT[3] - ctrim; }
                }
              }
              if (nb < gbT[2] - 0.05 || nr < gbT[3] - 0.05 || nl > gbT[1] + 0.05) {
                tf.geometricBounds = [gbT[0], nl, nb, nr];
                if (tf.overflows) tf.geometricBounds = gbT;
              }
            } catch (eTd) {}
          }
          setOpacity(tf, n.opacity);
          rotateNode(tf, n, (tfx1 + tfx2) / 2, (tfTop + tfBottom) / 2);
          regGroup(n, tf);
        }
      } catch (e) {
        log("ERROR building '" + n.name + "' (page " + (p + 1) + "): " + e.message + " @jsx:" + e.line);
        if (n.kind === "container") {
          CONTAINER_GEOMETRY.push('{"page":' + (p + 1) + ',"node":' + jsonString(n.sourceId) +
            ',"sourceType":' + jsonString(n.sourceType) + ',"expectedBounds":[' + [n.y, n.x, n.y + n.height, n.x + n.width].join(",") +
            '],"actualBounds":[0,0,0,0],"measurable":false,"reason":' + jsonString(e.message) + '}');
        } else if (n.kind === "text") {
          for (var failedLine = 0; failedLine < n.visualLines.length; failedLine++) {
            var failedSource = n.visualLines[failedLine];
            TEXT_GEOMETRY.push('{"page":' + (p + 1) + ',"node":' + jsonString(n.id || n.name) +
              ',"line":' + (failedLine + 1) + ',"expectedX":' + Number(failedSource.x) +
              ',"expectedBaseline":' + Number(failedSource.baselineY) + ',"actualX":0,"actualBaseline":0,"measurable":false,"reason":' +
              jsonString("text frame build failed: " + e.message) + '}');
          }
        }
      }
    }
    try {
      if (CONTAINER_ITEMS.length > 1) {
        var sourceGroup = sprRef.groups.add(CONTAINER_ITEMS);
        sourceGroup.name = "Figma source containers - " + sp.name;
        try { sourceGroup.nonprinting = true; } catch (eGroupPrint) {}
      }
    } catch (eContainerGroup) {
      log("SOURCE CONTAINER GROUP FAILED on page " + (p + 1) + ": " + eContainerGroup.message);
    }
    // Rotated containers: group members and rotate around the group center,
    // matching CSS transform-origin center on the container.
    var rgs = sp.rotGroups || [];
    for (var rg2 = 0; rg2 < rgs.length; rg2++) {
      var members = GROUP_MAP[rgs[rg2].id] || [];
      try {
        if (members.length > 1) {
          var grp = sprRef.groups.add(members);
          rotateCenter(grp, rgs[rg2].deg);
        } else if (members.length === 1) {
          rotateCenter(members[0], rgs[rg2].deg);
        }
      } catch (eG) {
        log("ERROR rotating group " + rgs[rg2].id + ": " + eG.message);
      }
    }
    GROUP_MAP = {};

    for (var w = 0; w < sp.warnings.length; w++) log("WARN p" + (p + 1) + ": " + sp.warnings[w]);
  }

  // Save native .indd + IDML + PNG proofs
  if (PRESET) {
    try { doc.pasteboardPreferences.pasteboardMargins = ["160pt", "96pt"]; } catch (ePb2) {}
  }
  var inddFile = new File(OPTS.outDir + "/" + SCENE.docName + ".indd");
  // A previous export of this same file may still be open (e.g. for review) -
  // close only that stale copy, never any other document.
  for (var di = app.documents.length - 1; di >= 0; di--) {
    var od = app.documents.item(di);
    if (od === doc) continue;
    try {
      if (od.saved && String(od.fullName.fsName) === String(inddFile.fsName)) od.close(SaveOptions.NO);
    } catch (eCl) {}
  }
  doc.save(inddFile);
  doc.exportFile(ExportFormat.INDESIGN_MARKUP, new File(OPTS.outDir + "/" + SCENE.docName + ".idml"));

  app.pngExportPreferences.exportResolution = PRESET ? 144 : 72;
  app.pngExportPreferences.antiAlias = true;
  app.pngExportPreferences.transparentBackground = false;
  app.pngExportPreferences.pngQuality = PNGQualityEnum.MAXIMUM;
  app.pngExportPreferences.pngColorSpace = PNGColorSpaceEnum.RGB;
  app.pngExportPreferences.pngExportRange = PNGExportRangeEnum.EXPORT_RANGE;
  for (var pg = 0; pg < doc.pages.length; pg++) {
    app.pngExportPreferences.pageString = String(pg + 1);
    doc.exportFile(ExportFormat.PNG_FORMAT, new File(OPTS.outDir + "/proof-" + (pg + 1) + ".png"));
  }

  doc.close(SaveOptions.YES);
  log("DONE");
}

try {
  main();
} catch (err) {
  log("FATAL: " + err.message + " (line " + err.line + ")");
}
writeLog();
`;
}
